[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags = -std=c++11
monitor_speed = 115200
lib_deps = 
	autowp/autowp-mcp2515@^1.2.1
	pololu/JrkG2@^1.1.0
	Wire
	mike-matera/ArduinoSTL
